service:
  name: sls-convert-pdf2img
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  s3:
    port: 8000
    directory: ./s3_local

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: stg
  region: ap-northeast-1
  profile: chiyell


functions:
  s3hook:
    handler: handler.s3hook
    events:
      - s3:
          bucket: local-bucket
          # bucket: chiyell-development
          events:
            - "s3:ObjectCreated:*"
          rules:
            - prefix: docs/
            - suffix: .pdf
          existing: true
